server:
  port: 9001

spring:
  application:
    name: house-service
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
    show_sql: false
    database: mysql
    hibernate:
      ddl-auto: create
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 200MB

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://20.214.170.222:8761/eureka

springdoc:
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  version: v1.0.0
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /bus/v3/api-docs
  cache:
    disabled: true
  packages-to-scan: com.nanum.houseservice

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

