server:
  port: 9001

spring:
  application:
    name: house-service
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
    show_sql: false
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  version: v1.0.0
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /bus/v3/api-docs
  cache:
    disabled: true
  packages-to-scan: com.nanum.houseservice