server:
  port: 0

spring:
  application:
    name: house-service
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
    show_sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 200MB
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.35.80.242:8761/eureka

springdoc:
  api-docs:
    path: /openapi/house-service
    groups:
      enabled: true
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  version: v1.0.0
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /bus/v3/api-docs
  cache:
    disabled: true
  packages-to-scan: com.nanum

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, info, metrics, prometheus

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error